language: php

# Run on container environment (needed for trais caching feature)
sudo: false

matrix:
  include:
      - php: 7.1

# Cache composer files for faster test times
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  # Remove xdebug module as it is not required but slows down composer and phpunit
  - phpenv config-rm xdebug.ini
  # Attempt to use Github oAuth token, if available, to avoid their public ratelimit
  - if [ -n "$GH_ACCESS_TOKEN" ]; then git config --global github.accesstoken $GH_ACCESS_TOKEN; fi;
  - if [ -n "$GH_ACCESS_TOKEN" ]; then composer config github-oauth.github.com $GH_ACCESS_TOKEN; fi;
  # Composer only updated in TravisCI containers when they build their images every month or so
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist

script:
  - phpunit
  - vendor/bin/phpstan analyse --level max src/ tests/
